spring:
  application:
    name: department-service
server:
  port: 8082
  h2:
    console.enable: true
  datasource:
    url: jdbc:h2:mem:department_db
    driverClassName: org.h2.Driver
    username: sa
    password: password
    console:
      enabled: true
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  eureka:
    instance:
      client:
        serviceUrl.defaultZone=http://localhost:8761/eureka/
